package org.owasp.astf.reporting;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.format.DateTimeFormatter;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.owasp.astf.core.result.Finding;
import org.owasp.astf.core.result.ScanResult;
import org.owasp.astf.core.result.Severity;

/**
 * Generates security scan reports in HTML format.
 */
public class HtmlReportGenerator implements ReportGenerator {
    private static final Logger logger = LogManager.getLogger(HtmlReportGenerator.class);
    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public String generate(ScanResult result) throws IOException {
        Map<Severity, Long> summary = result.getSeveritySummary();
        StringBuilder sb = new StringBuilder();

        sb.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        sb.append("  <meta charset=\"UTF-8\">\n");
        sb.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        sb.append("  <title>OWASP ASTF Security Report</title>\n");
        sb.append("  <style>\n");
        sb.append(getCss());
        sb.append("  </style>\n</head>\n<body>\n");

        // Header
        sb.append("<div class=\"header\">\n");
        sb.append("  <h1>OWASP API Security Testing Framework</h1>\n");
        sb.append("  <p>Security Scan Report</p>\n");
        sb.append("</div>\n");

        // Summary card
        sb.append("<div class=\"container\">\n");
        sb.append("<div class=\"summary\">\n");
        sb.append("  <h2>Scan Summary</h2>\n");
        sb.append("  <p><strong>Target:</strong> ").append(esc(result.getTargetUrl())).append("</p>\n");
        if (result.getScanStartTime() != null) {
            sb.append("  <p><strong>Start:</strong> ").append(result.getScanStartTime().format(FORMATTER)).append("</p>\n");
        }
        if (result.getScanEndTime() != null) {
            sb.append("  <p><strong>End:</strong> ").append(result.getScanEndTime().format(FORMATTER)).append("</p>\n");
        }
        sb.append("  <p><strong>Total Findings:</strong> ").append(result.getTotalFindingsCount()).append("</p>\n");
        sb.append("</div>\n");

        // Severity breakdown
        sb.append("<div class=\"severity-grid\">\n");
        for (Severity sev : Severity.values()) {
            long count = summary.getOrDefault(sev, 0L);
            String cssClass = "severity-" + sev.name().toLowerCase();
            sb.append("  <div class=\"severity-card ").append(cssClass).append("\">\n");
            sb.append("    <div class=\"count\">").append(count).append("</div>\n");
            sb.append("    <div class=\"label\">").append(sev.name()).append("</div>\n");
            sb.append("  </div>\n");
        }
        sb.append("</div>\n");

        // Findings table
        if (!result.getFindings().isEmpty()) {
            sb.append("<h2>Findings</h2>\n");
            for (Finding f : result.getFindings()) {
                String sevClass = "badge-" + f.getSeverity().name().toLowerCase();
                sb.append("<div class=\"finding\">\n");
                sb.append("  <div class=\"finding-header\">\n");
                sb.append("    <span class=\"badge ").append(sevClass).append("\">")
                  .append(f.getSeverity().name()).append("</span>\n");
                sb.append("    <strong>").append(esc(f.getTitle())).append("</strong>\n");
                sb.append("    <span class=\"test-id\">").append(esc(f.getTestCaseId())).append("</span>\n");
                sb.append("  </div>\n");
                sb.append("  <p><strong>Endpoint:</strong> <code>").append(esc(f.getEndpoint())).append("</code></p>\n");
                sb.append("  <p>").append(esc(f.getDescription())).append("</p>\n");
                if (f.getEvidence() != null) {
                    sb.append("  <p><strong>Evidence:</strong> <code>").append(esc(f.getEvidence())).append("</code></p>\n");
                }
                sb.append("  <div class=\"remediation\">\n");
                sb.append("    <strong>Remediation:</strong> ").append(esc(f.getRemediation())).append("\n");
                sb.append("  </div>\n");
                sb.append("</div>\n");
            }
        } else {
            sb.append("<div class=\"no-findings\">No security issues were detected during the scan.</div>\n");
        }

        sb.append("</div>\n"); // container
        sb.append("<div class=\"footer\">Generated by OWASP API Security Testing Framework v1.0.0</div>\n");
        sb.append("</body>\n</html>\n");

        return sb.toString();
    }

    @Override
    public void generateToFile(ScanResult result, String outputPath) throws IOException {
        String content = generate(result);
        Files.write(Paths.get(outputPath), content.getBytes(StandardCharsets.UTF_8));
        logger.info("HTML report written to {}", outputPath);
    }

    private String getCss() {
        return """
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                   margin: 0; padding: 0; background: #f5f5f5; color: #333; }
            .header { background: #2c3e50; color: white; padding: 24px 32px; }
            .header h1 { margin: 0; font-size: 1.8em; }
            .header p { margin: 4px 0 0; opacity: 0.8; }
            .container { max-width: 1100px; margin: 24px auto; padding: 0 24px; }
            .summary { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px;
                       box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .summary h2 { margin-top: 0; color: #2c3e50; }
            .severity-grid { display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }
            .severity-card { flex: 1; min-width: 100px; border-radius: 8px; padding: 16px;
                             text-align: center; color: white; }
            .severity-card .count { font-size: 2.5em; font-weight: bold; }
            .severity-card .label { font-size: 0.85em; text-transform: uppercase; letter-spacing: 1px; }
            .severity-critical { background: #c0392b; }
            .severity-high     { background: #e67e22; }
            .severity-medium   { background: #f39c12; }
            .severity-low      { background: #27ae60; }
            .severity-info     { background: #2980b9; }
            .finding { background: white; border-radius: 8px; padding: 20px; margin-bottom: 16px;
                       box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-left: 4px solid #ccc; }
            .finding-header { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; flex-wrap: wrap; }
            .badge { padding: 4px 10px; border-radius: 4px; font-size: 0.75em; font-weight: bold;
                     color: white; text-transform: uppercase; }
            .badge-critical { background: #c0392b; }
            .badge-high     { background: #e67e22; }
            .badge-medium   { background: #f39c12; }
            .badge-low      { background: #27ae60; }
            .badge-info     { background: #2980b9; }
            .test-id { font-size: 0.8em; color: #666; background: #f0f0f0; padding: 2px 6px;
                       border-radius: 3px; font-family: monospace; }
            .remediation { background: #e8f4fd; border-left: 3px solid #2980b9; padding: 10px 14px;
                           border-radius: 0 4px 4px 0; margin-top: 10px; }
            code { background: #f0f0f0; padding: 2px 5px; border-radius: 3px; font-family: monospace;
                   font-size: 0.9em; word-break: break-all; }
            .no-findings { background: #d5f5e3; border-radius: 8px; padding: 24px;
                           text-align: center; color: #1e8449; font-size: 1.1em; }
            .footer { text-align: center; padding: 24px; color: #999; font-size: 0.85em; }
            h2 { color: #2c3e50; }
            """;
    }

    private String esc(String value) {
        if (value == null) return "";
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }
}
